import { MODEL_IMAGE_MNIST } from "./MODEL_MNIST";
import { MODEL_IMAGE_MOBILENET } from "./MODEL_MOBILENET";
import { MODEL_IMAGE_RESNET } from "./MODEL_RESNET";

export {
  MODEL_IMAGE_MNIST,
  MODEL_IMAGE_MOBILENET,
  MODEL_IMAGE_RESNET
}