import I_MODEL_IMAGE_CLASSIFICATION from './_model'
import MODEL_IMAGE_MNIST from './MODEL_IMAGE_MNIST'
import MODEL_IMAGE_KMNIST from './MODEL_IMAGE_KMNIST'
import MODEL_IMAGE_MOBILENET from './MODEL_IMAGE_MOBILENET'
import MODEL_IMAGE_RESNET from './MODEL_IMAGE_RESNET'

const MAP_IC_CLASSES = {
  [MODEL_IMAGE_MNIST.KEY]    : MODEL_IMAGE_MNIST,
  [MODEL_IMAGE_KMNIST.KEY]   : MODEL_IMAGE_KMNIST,
  [MODEL_IMAGE_MOBILENET.KEY]: MODEL_IMAGE_MOBILENET,
  [MODEL_IMAGE_RESNET.KEY]   : MODEL_IMAGE_RESNET,
}
export {
  MAP_IC_CLASSES,

  I_MODEL_IMAGE_CLASSIFICATION,
  MODEL_IMAGE_MNIST,
  MODEL_IMAGE_KMNIST,
  MODEL_IMAGE_MOBILENET,
  MODEL_IMAGE_RESNET
}