import I_MODEL_OBJECT_DETECTION from './_model'
import { MODEL_1_FACE_DETECTOR } from './MODEL_1_FACE_DETECTOR'
import { MODEL_2_FACE_MESH } from './MODEL_2_FACE_MESH'
import { MODEL_3_MOVE_NET_POSE_NET } from './MODEL_3_MOVE_NET_POSE_NET'
import { MODEL_4_COCO_SSD } from './MODEL_4_COCO_SSD'
import { MODEL_5_FACE_API } from './MODEL_5_FACE_API'
import { MODEL_6_HAND_SIGN } from './MODEL_6_HAND_SIGN'

const MAP_OD_CLASSES = {
  [MODEL_1_FACE_DETECTOR.KEY]    : MODEL_1_FACE_DETECTOR,
  [MODEL_2_FACE_MESH.KEY]        : MODEL_2_FACE_MESH,
  [MODEL_3_MOVE_NET_POSE_NET.KEY]: MODEL_3_MOVE_NET_POSE_NET,
  [MODEL_4_COCO_SSD.KEY]         : MODEL_4_COCO_SSD,
  [MODEL_5_FACE_API.KEY]         : MODEL_5_FACE_API,
  [MODEL_6_HAND_SIGN.KEY]        : MODEL_6_HAND_SIGN,
}
export {
  MAP_OD_CLASSES,

  I_MODEL_OBJECT_DETECTION,
  MODEL_1_FACE_DETECTOR,
  MODEL_2_FACE_MESH,
  MODEL_3_MOVE_NET_POSE_NET,
  MODEL_4_COCO_SSD,
  MODEL_5_FACE_API,
  MODEL_6_HAND_SIGN,
}