import I_MODEL_OBJECT_DETECTION from './_model'
import { MODEL_FACE_DETECTOR } from './MODEL_FACE_DETECTOR'
import { MODEL_FACE_MESH } from './MODEL_FACE_MESH'
import { MODEL_MOVE_NET_POSE_NET } from './MODEL_MOVE_NET_POSE_NET'
import { MODEL_COCO_SSD } from './MODEL_COCO_SSD'

const MAP_OD_CLASSES = {
  [MODEL_FACE_DETECTOR.KEY]    : MODEL_FACE_DETECTOR,
  [MODEL_FACE_MESH.KEY]        : MODEL_FACE_MESH,
  [MODEL_MOVE_NET_POSE_NET.KEY]: MODEL_MOVE_NET_POSE_NET,
  [MODEL_COCO_SSD.KEY]         : MODEL_COCO_SSD,
}
export {
  MAP_OD_CLASSES,

  I_MODEL_OBJECT_DETECTION,
  MODEL_FACE_DETECTOR,
  MODEL_FACE_MESH,
  MODEL_MOVE_NET_POSE_NET,
  MODEL_COCO_SSD
}