import { MODEL_FACE_DETECTOR } from "./MODEL_FACE_DETECTOR";
import { MODEL_FACE_MESH } from "./MODEL_FACE_MESH";
import { MODEL_MOVE_NET_POSE_NET } from "./MODEL_MOVE_NET_POSE_NET";
import { MODEL_COCO_SSD } from "./MODEL_COCO_SSD";

export {
  MODEL_FACE_DETECTOR,
  MODEL_FACE_MESH,
  MODEL_MOVE_NET_POSE_NET,
  MODEL_COCO_SSD
}