import I_MODEL_TABULAR_CLASSIFICATION from './_model'
import MODEL_CAR from './MODEL_CAR'
import MODEL_IRIS from './MODEL_IRIS'
import MODEL_LYMPHOGRAPHY from './MODEL_LYMPHOGRAPHY.js'

const MAP_TC_CLASSES = {
  [MODEL_CAR.KEY]         : MODEL_CAR,
  [MODEL_IRIS.KEY]        : MODEL_IRIS,
  [MODEL_LYMPHOGRAPHY.KEY]: MODEL_LYMPHOGRAPHY,
}

export {
  MAP_TC_CLASSES,

  I_MODEL_TABULAR_CLASSIFICATION,
  MODEL_CAR,
  MODEL_IRIS,
  MODEL_LYMPHOGRAPHY
}