// 0 - 1 --> 0 - 100
const DEFAULT_LEARNING_RATE = 1
// 1 - Inf(1000)
const DEFAULT_NUMBER_OF_EPOCHS = 20
// 0 - 1 --> 0 - 100
const DEFAULT_TEST_SIZE = 10
// TYPE_OPTIMIZER.key
const DEFAULT_OPTIMIZER = 'train-adam'
// TYPE_LOSSES.key
const DEFAULT_LOSS = 'losses-meanSquaredError'
// TYPE_METRICS.key
const DEFAULT_METRICS = ['metrics-meanSquaredError']

export {
  DEFAULT_LEARNING_RATE,
  DEFAULT_NUMBER_OF_EPOCHS,
  DEFAULT_TEST_SIZE,
  DEFAULT_OPTIMIZER,
  DEFAULT_LOSS,
  DEFAULT_METRICS,
}